### ISSUE TITLE
Repository link on npmjs.com

### ISSUE THREAD

**Issue by manuc66** [BibbyChung/sequelize-adapter#1]
Hi,

I did not found easily the repository location from npmjs.com, maybe you could add it ?

Thanks

**Comment by BibbyChung** [comment]
Sorry for replying late. The link is https://www.npmjs.com/package/sequelize-adapter. ^&^

**Comment by manuc66** [comment]
I found the project from npmjs and I needed some search engine query to find this repository.

Currently on npmjs we have:
![image](https://user-images.githubusercontent.com/5827164/47486474-bde1d280-d840-11e8-9ee8-bf7caf2df1fc.png)

And I would have expected something similar to:
![image](https://screenshotscdn.firefoxusercontent.com/images/3d9221dd-92a6-43d3-9487-582a4c49d6cb.png)

Thanks

**Comment by BibbyChung** [comment]
done.. ^&^...thank you so much.

<img width="435" alt="screen shot 2018-10-26 at 12 15 57 am" src="https://user-images.githubusercontent.com/8520661/47515044-64b38680-d8b4-11e8-8c90-0370a0442da7.png">

**Comment by manuc66** [comment]
Thanks
